on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: npm install
    - name: Run tests
      continue-on-error: true
      uses: GabrielBB/xvfb-action@v1.4
      with:
        run: npm test
    - run: npm run package
    - uses: actions/upload-artifact@v2
      with:
        name: VSIX
        path: '*.vsix'
